# Generated by Django 6.0.2 on 2026-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Non lu'), ('read', 'Lu')], default='unread', max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='notificatio_user_id_c291d5_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx')],
            },
        ),
    ]
